### ISSUE TITLE
Renaming the sieves broken on FF

### ISSUE THREAD

**Issue by kuzn123** [TheFantasticWarrior/chrome-extension-imagus#14] opened 2023-04-19 16:27 UTC
SHIFT+RIGHT CLICK - just a normal RIGHT CLICK.

At the same time, renaming works fine on Chromium browsers. Perhaps it has something to do with using SHIFT+CLICK on the extension icon to access the Settings in FF?

**Comment by TheFantasticWarrior** [comment] 2023-04-27 05:45
sorry for late reply, it is caused by firefox feature https://bugzilla.mozilla.org/show_bug.cgi?id=897379, mind if I change it to normal right click?

**Comment by kuzn123** [comment] 2023-04-27 08:50
> mind if I change it to normal right click?

If you mean renaming sieves, then it would probably be even better. The standard context menu is not needed there.

**Comment by TheFantasticWarrior** [comment] 2023-04-27 10:26
should be fixed https://github.com/TheFantasticWarrior/chrome-extension-imagus/releases/tag/v0.10.10

**Closed as completed by TheFantasticWarrior** 2023-04-27 10:26 UTC
Labels: solved

**Comment by kuzn123** [comment] 2023-04-27 11:06
Thanks, it works.
